### Date: 26-11-2019

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [3]:
list(iris.keys())

['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
iris_df = pd.DataFrame(iris.data,columns = iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
x = iris['data'][:,3:]
y = (iris['target']==0).astype(np.int)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
from sklearn.linear_model import LogisticRegression
logi_reg = LogisticRegression()
logi_reg.fit(x,y)

C:\Users\IIIT-rgukt\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
logi_reg.predict([[0.5],[0.4]])

array([1, 1])

In [9]:
import numpy as np
x_new = np.linspace(0,3,30).reshape(-1,1)
# probabilities for flowers with petal widths varying from 0 to 3 cm
# (-1,1) we want numpy to figure it out.
x_new

array([[0.        ],
       [0.10344828],
       [0.20689655],
       [0.31034483],
       [0.4137931 ],
       [0.51724138],
       [0.62068966],
       [0.72413793],
       [0.82758621],
       [0.93103448],
       [1.03448276],
       [1.13793103],
       [1.24137931],
       [1.34482759],
       [1.44827586],
       [1.55172414],
       [1.65517241],
       [1.75862069],
       [1.86206897],
       [1.96551724],
       [2.06896552],
       [2.17241379],
       [2.27586207],
       [2.37931034],
       [2.48275862],
       [2.5862069 ],
       [2.68965517],
       [2.79310345],
       [2.89655172],
       [3.        ]])

In [10]:
y_prob = logi_reg.predict_proba(x_new)
y_prob.round(3)

array([[0.061, 0.939],
       [0.089, 0.911],
       [0.128, 0.872],
       [0.182, 0.818],
       [0.251, 0.749],
       [0.336, 0.664],
       [0.433, 0.567],
       [0.536, 0.464],
       [0.635, 0.365],
       [0.724, 0.276],
       [0.799, 0.201],
       [0.857, 0.143],
       [0.9  , 0.1  ],
       [0.932, 0.068],
       [0.954, 0.046],
       [0.969, 0.031],
       [0.979, 0.021],
       [0.986, 0.014],
       [0.991, 0.009],
       [0.994, 0.006],
       [0.996, 0.004],
       [0.997, 0.003],
       [0.998, 0.002],
       [0.999, 0.001],
       [0.999, 0.001],
       [0.999, 0.001],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [1.   , 0.   ]])

In [11]:
import matplotlib.pyplot as plt
plt.plot(x_new,y_prob[:,1],'r-',label = 'Iris Setosa')
plt.plot(x_new,y_prob[:,0],'g--',label = 'Not Iris Setosa')
plt.xlabel("Petal width (cm)")
plt.ylabel("Probability")
plt.legend(loc ="center")
plt.show()

<Figure size 640x480 with 1 Axes>

## SoftMax Regression

In [12]:
x1 = iris["data"][:,(2,3)] # petal length, petal width
y1 = iris['target']

In [13]:
softmax_reg = LogisticRegression(multi_class = 'multinomial',solver = "lbfgs",C = 10)  # C --> is hyper parameter

In [14]:
softmax_reg.fit(x1,y1)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
softmax_reg.predict([[4.2,1.5]])

array([1])

In [16]:
softmax_reg.predict_proba([[4.2,1.5]]).round(3)

array([[0.001, 0.98 , 0.02 ]])